### ISSUE TITLE
Cannot find package from Jitpack

### ISSUE THREAD

**Issue by ArnyminerZ** [awxkee/avif-coder#17]
Hi, I'm trying to include the dependency from Jitpack, and Gradle can't manage to find it. I'm already using other Jitpack projects, so I don't think it's an issue with my configuration.

Anyway, here's what I'm using:
```toml
# libs.versions.toml

[versions]
auxkee-avif = "master-SNAPSHOT"

[libraries]
auxkee-avif-coder = { module = "com.github.awxkee:avif-coder", version.ref = "auxkee-avif" }

[plugins]
```
```kotlin
// build.gradle.kts

repositories {
    mavenCentral()
    maven("https://jitpack.io")
}

dependencies {
    implementation(libs.auxkee.avif.coder)
}
```
